### PR TITLE
Empty Rows/Columns Support 

### PR DESCRIPTION
**Pull request by ruyaoyao**
Hi, thank you for this wonderful plugin you made. 
I took a liberty making some changes, let me know if you are fine with it. 
Thanks.

### CODE REVIEW

**Comment by msarocha** [comment]
Great job mateuszamarkowski! Excellent!

Hi cslinmiso,
If use your implementation labels [ID,LABEL] dont work...

**Comment by cslinmiso** [comment]
@msarocha, it's been a while since last I modified it. I haven't got a chance to use the function you mentioned. I will try to see if it's fixable sometime next week. 

Thanks.

**Comment by msarocha** [comment]
How to delete a seatCharts object/data without reload page?
I use a modal to show a seatmap and need to change "map"  on each button modal click...

**Comment by mateuszmarkowski** [comment]
I think you could simply remove the map's element. This will remove the object together with its data. Yet if you generate a legend, you will need to remove the legend's element as well.

**Comment by sitrsh12** [comment]
Hi msarocha..
Could u able to push the seat inside array on button click, each click push seats without page reload? Please help

**Pull request closed without merging**
